// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whwhhehypiuryfssbrqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indod2hoZWh5cGl1cnlmc3NicnFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Nzk0NjYsImV4cCI6MjA2NjM1NTQ2Nn0.xtFvX8ZbI1iNW9MOqc7k5kKg5IbYihjvfw4uA-h6z04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);